### ISSUE TITLE
Allow families to search for children by region

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#159]
In child profile gallery, add ability to query by the region the child is associated with.

**Comment by n-devr** [comment]
Couple questions:

1. How do we determine a child's region? Do we leverage associated SW's region?
2. Where should this field be added on child search form?

**Comment by bchiaruttini** [comment]
Hi –

1.)    Yes the child’s region is pulled from the adoption worker’s region

2.)    How about under Limit Search section. Left column could say Region of Social Worker: and right column would be drop down with No Restrictions being the default and then could multi-select from list of regions

**Comment by n-devr** [comment]
This is complete and ready for review in `develop`

**Comment by bchiaruttini** [comment]
@n-devr is it possible to make the drop down for regions multi-select?  If not, this works but ideally the worker could select multiple regions in one search.

**Comment by n-devr** [comment]
We can definitely achieve multi-select functionality for regions - the one gotcha is that we don't have a multi-select dropdown component on the front end like we do on the reporting dashboard.  The quickest solution would be to convert the dropdown to a list of checkboxes so that it'd work like the race/language fields, but I can also implement a multi-select component for the front end if you'd prefer.

Since this is currently working I'll push it to `prod` with the current batch of code, but will keep the story in progress until the multi-select functionality is implemented.

**Comment by bchiaruttini** [comment]
got it - the checkbox method could definitely work if easiest.
