### ISSUE TITLE
Unrecognized email users

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#187]
When SW or prospective parent attempt to create account their email is not being recognized, even when no duplicate record or nothing unusual about account.   Joe will provide one parent and one social worker example.

**Comment by communicationsmare** [comment]
This issue appears to be resolved after implementing Jared's prior advice about the error coming from the web browser vs. the database. Outreach to users with prior issues did not yield a request for additional support. No issues reported since we started advising users to be sure that emails were all drop case. Closing issue.
