### ISSUE TITLE
Intellectual, Emotional and Physical Needs dimensions in Reporting Suite

### ISSUE THREAD

**Issue by joesmare** [mareinc/mare#312]
Lower/Upper Limits for Age, Intellectual, Social and Emotional Needs Assessment: Reporting Database
There is an anomolie with regard to searching for certain conditions:
EXAMPLE:
When looking for families in Keystone with a defined range of ‘Maximum Intellectual Needs’ that is set to ‘Severe’ I show two active families (active=‘registered with MARE’ is checked and ‘status’ is ‘active’ plus they are ‘not closed’)

 
KEYSTONE SEARCH RESULTS
NOT closed×maximum intellectual needs is severe×is active×registered with MARE×
Showing 2 Families

Danielle and Steven Bruni - 44299	
Sandwich
Massachusetts	

Theresa Cote - 43799	
Dedham
Massachusetts	

When trying to search for these families using the reporting tool (reverse engineering the match) I can’t get them to come-up. Same has been the case with any highly restrictive search in any needs dimension, but not at any level (seems to mostly apply to 'severe'). Notably there are less of these families...but they should show-up, unless I missed an excluding factor.

I’ve tried to play with all of the various combination of settings, tried opening up the search, I’ve also tried using lower limit of ‘severe’ to upper limit of ‘any’ as well as lower limit of ‘severe’ and upper limit of ‘severe’ to no avail.

RELATED:
Lastly, there are different outcomes for setting lower limit at ‘mild’ and upper limit at ‘mild’ vs. ‘mild’ to ‘any’.

**Comment by n-devr** [comment]
After fixing the Child Status issue (#316) this functionality is behaving a lot closer to our expectations.

I investigated the two families listed in the story and the reason they are not showing is because neither one has a 'Family Constellation' defined.  If you remove all family constellation criteria from the search on the dashboard they will show up as expected.  How should we treat families with no constellation specified?

> Lastly, there are different outcomes for setting lower limit at ‘mild’ and upper limit at ‘mild’ vs. ‘mild’ to ‘any’.

As I understand the logic, this is actually functioning as designed.  If you set mild/mild, you are only searching for families that have set max needs to mild.  If you set mild/any you are searching for families that have set max needs to mild/moderate/severe.  Does that make sense?

@joesmare
