### ISSUE TITLE
Inaccuracies in child profile search 

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#385]
On Waiting Child profile page, you can view all children. If user selects "Modify Search" but then changes no criteria and hits submit, only a partial list of children is returned, instead of all children.

Examples:  Sib group 5215 and 5217 (Heily and Heliarus) are viewable on full list, but not when you modify search without changing conditions, or modify search to sibling groups of two females.  When you select clear search, they appear again.

The same happens for singleton child 5394 (Tylor).

**Comment by joesmare** [comment]
I have a specific example of this phenomenon: 

Bryson & Logan (7606 & 7607)
Profile appears in general search. When you create a specific search with matching criteria the profile does not render.

**Comment by n-devr** [comment]
Speaking with Bridget we came up with two content changes for the family section of the search form:

- [ ] Family Profile becomes Adoptive Family Profile
- [ ] Family Type becomes Recommended Family Type

I will make these changes while solving the search issue.

**Comment by n-devr** [comment]
@bchiaruttini @joesmare Just following up on my findings on this issue:

When you click Search from the "Modify Search" form some additional filtering logic is run to determine which children to display in the gallery, which is the root cause for some of the children not showing up in this case.  More specifically, the issues occur if the "other family constellation consideration" fields are set on the child model.  If a child has any "other family constellation considerations" set, they _must_ match the values in the search form for them to display in the gallery.  If the search form is empty, the values will never match, so the children don't display.  

I can prevent the children from being hidden when the search form is empty, but I'm not sure the logic that's in place for the "other family constellation considerations" makes sense.  I'll take some time to document the current logic tomorrow or Friday so we can determine if it's correct of if we need to update it.

**Comment by joesmare** [comment]
Thank you @n-devr. I agree with part A: allow for the fields at the bottom of the search form to be empty when executing a search. 

Regarding part B: Search criteria. In speaking with you yesterday afternoon about this issue, I expressed concern with the way that we qualify 'Placement Considerations' in 'CHILD RECORD'. Specifically, I am unable to understand how we can qualify a search against the 'Childless home acceptable/required' marker (this should be separated into 'Childress home acceptable' and a separate marker for 'Childless home required')  and also how we qualify against both that/those marker(s) and the opposing marker of 'Multi-child home acceptable'. It seems to me that the query should reflect matches for a child that must be placed in a home without other children (='Childless home required'), can be placed in a childless home (='Childless home acceptable' and 'Multi-child home acceptable')  but even with this correction we didn't discuss the implications of age alignment of the children being presented (i.e. "Child can be placed with older/younger siblings, child must be youngest, child must be oldest, etc.). Since I did not work on this part of the build I cannot provide any context for how/why it was constructed the way it was, but I think if we are going to take the time to fix this that at least for part B we should answer these questions and make sure that the model can handle the logic of how we qualify children on the back end. @bchiaruttini thoughts?

**Comment by n-devr** [comment]
I totally agree on the ambiguity of the "other family constellation consideration" fields.  When inspecting the child model I didn't see the acceptable vs required delineation for those options, but I do remember Jeremy bringing that up.  Either way, I do think we should better understand the intention for the  "other family constellation consideration" fields before rethinking any of the logic for the search form.  I do have some time this morning/afternoon so I'll document the logic as it currently stands.

**Comment by joesmare** [comment]
@n-devr it lives in 'CHILD REORD' under 'Placement Considerations'  in field 'Other family constellations' drop-down menu. Thank you for documenting the logic as it stands, We can review and pick-up from there.

**Comment by n-devr** [comment]
@joesmare sorry if I was unclear - I know where the "other family constellation consideration" fields are, I didn't follow where the acceptable vs required delineation came from.  If that exists somewhere I assume it would impact the logic we implement regarding the selections, so I wanted to call that out.

**Comment by joesmare** [comment]
apologies @n-devr  we are saying the same thing. I'm unclear why it was built this way or where the delineation comes from. A point of future discussion. TY

**Comment by n-devr** [comment]
The erroneous filtering of sibling groups is now fixed and profiles will not be filtered out if nothing was changed on the "Modify Search" menu.  That being said, the search/filter logic when those fields are actually set still requires investigation.

### Other Family Constellation Consideration Search Logic ####

This logic is only run after opening the "Modify Search" menu and clicking search from that screen.

If a child has one or more _other family constellation considerations_ set on their record in the database, the following filtering logic will be applied to all children/sibling groups in the gallery.  I'll break the logic down by the behavior for each _other family constellation consideration_.

**multi-child home**

- If _multi-child home_ is set on a child model **and** _number of children in home_ is set to 0 on the search form...
   - the child will be hidden in the gallery
- If _multi-child home_ is set on a child model **and** _number of children in home_ is not set **or** is set to any number other than 0...
   - the child will be displayed in the gallery
- If _multi-child home_ is not set on a child model...
   - the child will be displayed in the gallery

**childless home**

- If _childless home_ is set on a child model **and** _number of children in home_ is set to 0 on the search form **or** is not set on the search form...
   - the child will be displayed in the gallery
- If _childless home_ is set on a child model **and** _number of children in home_ is set to any number other than zero...
   - the child will be hidden in the gallery
- If _childless home_ is not set on a child model...
   - the child will be displayed in the gallery

**younger children acceptable**

 - if _younger children acceptable_ is set on a child model **and** _Age of youngest child in home_ is set to a number that is less than or equal to the child's age (or youngest child's age in a sibling group) **or** _Age of youngest child in home_ is not set on the search form...
    - the child will be displayed in the gallery
 - if _younger children acceptable_ is set on a child model **and** _Age of youngest child in home_ is set to a number that is greater than the child's age (or youngest child's age in a sibling group)...
   - the child will be hidden in the gallery
- If _younger children acceptable_ is not set on a child model...
   - the child will be displayed in the gallery

**older children acceptable**

 - if _older children acceptable_ is set on a child model **and** _Age of oldest child in home_ is set to a number that is greater than or equal to the child's age (or oldest child's age in a sibling group) **or** _older children acceptable_ is not set on the search form...
    - the child will be displayed in the gallery
 - if _older children acceptable_ is set on a child model **and** _Age of oldest child in home_ is set to a number that is less than the child's age (or oldest child's age in a sibling group)...
   - the child will be hidden in the gallery
- If _older children acceptable_ is not set on a child model...
   - the child will be displayed in the gallery

**CANNOT be in home with pets**

 - if _CANNOT be in home with pets_ is set on a child model **and** _Pets in the home_ is checked on the search form
    - the child will be hidden in the gallery
 - if _CANNOT be in home with pets_ is not set on a child model **or** _Pets in the home_ is not checked on the search form
    - the child will be displayed in the gallery


Other than the Pets consideration logic (which makes sense to me), I'm not sure that the rules being applied to hide children/sib groups are intended.  Please let me know if this logic should remain in place or if you'd like to modify it in some way.  Hopefully I was able to break it down clearly enough for a decision to be made, but of course let me know if you have any questions @bchiaruttini  @joesmare !

**Comment by joesmare** [comment]
@n-devr  this is infinitely helpful in assessing the current build. @bchiaruttini let's review comprehensively and give @n-devr any corrections to the current logic. 
****@n-devr  can I assume from this assessment then that the criterion of 'Childress home acceptable/required' in a child record will only show/return that child to a family with a record indicating that they have zero children? If so, what does it then do if the child record also has 'multi-child home' selected? The logic here is confusing...if a child has both selected, is the search advanced enough to employ an either/or selection or is it utilizing linear logic of must equal to both? That would potentially be a problem for a number of child records where both are selected and may potentially cause this phenomenon we're seeing. A family record won't ever be both a childless home and a home with children.

**Comment by n-devr** [comment]
Happy to hear the write-up proved valuable!

If a child has the _childless home_ specified under _other family constellation considerations_ in their model, they will be displayed in the child gallery when either of 2 conditions are true:

1. The user has not specified any value for _Number of children in home_ on the search form.
2. The user has specified 0 for the _Number of children in home_ on the search form.

The question you posed about how the logic works when multiple _other family constellation considerations_ are in play is also important.  The conditions are evaluated together, and if any of them are true, then the child is shown in the gallery.  

So, for example, if a child record has both the _childless home_ and _multi-child home_ considerations specified and the user sets the _Number of children in home_ value to 0, the logic would run as follows:

Test for _childless home_: true  (because the user specified a value, and the value was 0)
Test for _multi-child home_: false (because the user specified a value, and the value was not any number other than 0)
Should the child display in gallery? Yes - because one of the tests passed.

I don't necessarily think the conditions being tied together like this makes sense, but I will leave the final decision to you.  As always, let me know if you have any questions!

**Comment by joesmare** [comment]
@bchiaruttini  Part A is resolved. I neglected to have a conversation with you about Part B, which will remain open until we decide if any logic changes are needed. I'll set an appointment with you for next Monday to discuss this.

**Comment by bchiaruttini** [comment]
reviewed and existing logic does not appear to be barrier at this time.
