### ISSUE TITLE
External SW load of community event (non-MAPP)

### ISSUE THREAD

**Issue by joesmare** [mareinc/mare#427]
There are reported errors regarding the loading of non-MARE external events at the web portal. Apparently MAPP training loads fine, but other events such as community-based learning sessions, etc. cause an error when loaded and don't render. 

A specific example was given by Alisha Patrick (an active SW user) on 1/27/20 at 5:09 PM

Please investigate and correct the issue.

**Comment by n-devr** [comment]
Happy to take a look but I'm not sure I follow where to do so.  Is [this](https://www.mareinc.org/events/partner-hosted-events) the list of "non-MARE external events"?

I can open all of them and they load normally when logged in as an Admin or a Social Worker.

**Comment by joesmare** [comment]
My apologies @n-devr . Much of the language that we have is used to explain things differently externally and internally, and the word "load" is a perfect example of that.  What it should have read is that someone was trying to UPLOAD details for an event to the website, while logged-in as an SW. She was able to upload a MAPP training, but then had issue trying to upload a (non-mare) partner-hosted event. 

In thinking about this and in speaking with Jeremy it seems like this may be an old issue that we never addressed as he (is able to and does) manually loads these types of events getting the info. through direct outreach from workers. This is the first one I have gotten directly, and thus is raising the question. 

We were wondering if it has to do with the file path associated with "Partner Hosted Events"  since we changed that label a while back? Could it be that the code was never changed to reflect this change? Not sure what else it may be (or that it actually ever worked), but in theory, if loading MAPP training works then this should too as it is the same logic and process flow. Happy to connect by phone as necessary.

**Comment by n-devr** [comment]
No worries @joesmare - I understand the issue much more clearly now.  I can investigate the logic to determine if the functionality regressed at some point or if it was never there at all and give an estimate on the effort to implement a fix.  Where does this fall on my priority list?  There seem to be a few bugs/investigation stories popping up so I just want to be sure I'm focusing on the right things.

**Comment by n-devr** [comment]
After doing some research I understand what's causing this issue and how to resolve it.  The code change itself will be fairly simple, but I will need a process/content decision from the team to move forward.  I will do my best to describe the issue and give you enough detail to make a decision for how to move forward.

### Issue Description
The _Event_ model has a `type` field, which renders as a dropdown in the Admin UI:
![image](https://user-images.githubusercontent.com/5726612/73770818-13e33c80-474b-11ea-834f-742fae25beed.png)
The values of the `type` field are hard-coded into the model (as the values you see above).

The AGENCY EVENT SUBMISSION page also has an `event type` dropdown, but the values for that dropdown are loaded from the _Event Type_ model.  Here are the current _Event Types_ that exist in production:
![image](https://user-images.githubusercontent.com/5726612/73771025-805e3b80-474b-11ea-8578-183e54c9d1c3.png)
If the `available on website` checkbox is checked then they appear in the event submission form.

When the _Event_ is being created after the form is submitted, the value in the `event type` dropdown is used as the value for the `type` of the _Event_.  If the user chooses a value that exists in the `event type` dropdown on the form, but **does not** exist in the hard coded `type` values of the _Event_ model, validation will fail and the _Event_ will not be created/saved.  Thus, MAPP Trainings work because they exist in both lists, but none of the other _Event Types_ that were created exist on the _Event_ model, so event creation will fail.

This code hasn't been updated in ~2 years, so my guess is that the _Event Types_ were recently updated or no one has tried to create a non-MAPP Training event from the front end.  

### Potential Solutions
The easiest way to solve this would be to bring the two event type lists in line with each other.   
 With a few lines of code this would be resolved with minimal risk.  The issue there is that if anyone creates a new _Event Type_ (and makes it visible on the website) it will automatically be added to the dropdown and if a SW tries to create an event with that type it will throw an error.  So there would need to be some process/oversight around adding new _Event Types_ to prevent similar issues in the future.

Another potential solution would be to use the _Event Types_ as the `type` directly within the _Event_ model.  It looks like that used to be the case, but a change was made a couple years ago to use a hard-coded list (I can't really tell why, maybe you guys remember?).  We could hook that functionality back up, which would make the system more robust moving forward.  However, the change could have a potential impact in any place the _Event_ model is used, because instead of the `type` being a simple piece of text, it would be a reference to another model.  So we'd have to update any place in the code where an _Event_ `type` is being read.  This would incur a lot of risk of breaking other functionality, and would require a thorough testing effort.

@joesmare please let me know how you'd like to proceed.

**Comment by joesmare** [comment]
@noah we had Jared consolidate the five event types to the three currently displayed. I think I understand what you are proposing and if I am correct, I suggest that we bring the two lists in alignment with each other as you suggest. I don't see a time when we would change the construct. If I am not answering clearly enough, or should you have any questions, give me a buzz on my cell. TY

**Comment by n-devr** [comment]
Sounds good @joesmare - I spoke with Bridget and we are going to update the `Event Types` to match the list hard-coded into the `Event` model

**Comment by bchiaruttini** [comment]
@n-devr Can you confirm that this story is complete and should be closed?

**Comment by bchiaruttini** [comment]
have not heard of this being an issue as of late
