### ISSUE TITLE
Issue with Inquiries not saving

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#429]
When staff are working in keystone and entering family inquiries, when hit submit button it just returns to the whole list of inquiries without saving.  If you hit refresh, the inquiry appears again, and then can be saved accurately.  Tested all different combinations of type of inquiry, method, etc. and does not seem to be any patterns.

This has been happening to multiple staff, multiple times per day for the past two weeks, however does not happen every single time.  It happened several different times on 1/24 around 2:57 for the Dostal Family (46797), if helpful to look at the logs.

**Comment by n-devr** [comment]
@bchiaruttini were you able to replicate the behavior yourself?  This is a case where seeing the bug in action is likely going to be necessary for me to diagnose the issue properly, because it sounds like there may be an issue with the Admin UI app itself, which runs locally in the browser of each user, making it hard for me to diagnose the issue without being able to reproduce it myself or see it first hand.  The server logs do not show any issues - there are a few entries for creating an Inquiry around the timestamp you provided:
`Jan 24 14:56:39 mare app/web.1: POST /keystone/api/inquiries/create 200 605.657 ms`
But they are all 200 status, which means the inquiry was created successfully.

I also see a large grouping of Inquiries that were created for the Dostal family around that time, most of which seem to be incomplete or inaccurate (sources from 2015, or no source at all):
![image](https://user-images.githubusercontent.com/5726612/73475141-c6875980-435d-11ea-8126-783362dab0bf.png)

This leads me to believe that the inquiries are being created and saved each time the user is hitting submit, but the page isn't refreshing properly to show the newly created record, or something to that effect, making it seem like it's not working.

If you or any of the staff notice it happening again can you take a screenshot of the behavior and try to provide very detailed steps on the clicks that caused it to happen?  E.g. was the new record being created from the list view or from another record view?  Was all of the data that was entered into the record saved properly?  Is there a delay between hitting Submit and the record popping up?

**Comment by bchiaruttini** [comment]
@n-devr So yes I viewed the error happening several times.  The many weird inquiries for the Dostal family was us playing around and testing different scenarios to see if there were any patterns. During this exercise, the behavior was intermittently expected and problematic.   Does it make sense for you to either remote into one of our screens and we can show you?  Or I can send screen shots as well, or can wait until Wed if you will be here in person.   But to answer some of your questions...I don't believe they were being saved correctly, b/c if you go back to the family's record or the inquiry list there is no record of them, unless they are saved the second time post-refresh. We experimented with creating inquiries both through the link in the family's record, as well as directly through the Inquiry model.   thanks.

**Comment by n-devr** [comment]
Thanks for the details @bchiaruttini - this is super helpful for me to diagnose the issue 👍 
I think scheduling some time next week to hop on a call/screenshare with you to recreate the behavior would make a lot of sense, I'll connect with you on Slack to find a time that works for both of us

**Comment by n-devr** [comment]
@bchiaruttini and I spoke about this issue and determined it seems likely that the Inquiries are being created/saved in the database, but the Admin UI isn't always directing the user to the newly created Inquiry.  If staff encounter this behavior they should grab a screenshot or note the URL of the browser at the time to help debug the issue further.

Putting this _On Hold_ until we receive additional feedback.

**Comment by bchiaruttini** [comment]
still an issue, can provide additional feedback.

**Comment by bchiaruttini** [comment]
tested this again - still happening but staff have work around.  @n-devr please add any relevant notes and we can close.

**Comment by n-devr** [comment]
### Issue Notes
This issue occurs because the admin ui does not wait for the database to complete an action (e.g. saving the record) before updating.  The Inquiry model has complex `pre-save` hooks that require database calls to be made, which takes time.  During the time that these calls are being made (so, before the model is fully saved), the admin ui tries to navigate to the page to display the newly created record.  Because the record does not exist yet, the admin UI brings the user back to the page to display all inquiries (still without the new record).  By this time, the new record has likely completed saving, so manually refreshing the page will bring the record into the list view.

### Why Defer
In order to fix this behavior an edit would have to be made to the Keystone Admin UI React app that is built into the Keystone package.
