### ISSUE TITLE
make child details printable

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#44]
### as a developer, I need to make child details pages printable so users and MARE staff can more easily share child information
---

### Tasks

- [x] create a print stylesheet targeting child details

### Definition of Done

- [ ] child details can be printed from the gallery and look good

**Comment by bchiaruttini** [comment]
This may have been resolved with Jeremy's new system of printing booklets?

**Comment by joesmare** [comment]
In thinking about the solution, we should simply set the parameters of the child(ren) specific pop-up window to print full-page to 8.5 x11 when a user clicks on the window and right mouse clicks and selects print.

**Comment by joesmare** [comment]
Add a print button to the modal window for a specific child. Add print button for MARE or SW user types. Format output for 8.5 x 11

**Comment by n-devr** [comment]
Based on our conversation yesterday I added support for printing only the modal window contents when a child details modal is opened in the gallery.  This will work if the user right clicks or uses a keyboard shortcut to print (e.g. `ctrl + p`).

If we need to go a step further and implement this fix for specific user-types only I can do that, but because the solution didn't require a dedicated print button I didn't think that was necessary.  Please let me know if my assumption was incorrect.

**Comment by joesmare** [comment]
Tested on IE, MS Edge and Chrome. You tested on Chrome and Safari. Should be good to push with the updates to the Reporting System this weekend. Thanks for your discovery and hard work on this one!
