### ISSUE TITLE
Covid-update banner

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#475]
Create banner that would display on the first page a user accesses in each session and would re-appear on each page until manually closed. Will link to hidden web page with full Covid message that can be updated.

For now will be hard coded - will discuss possibility of building within Keystone for future updates and uses.

**Comment by n-devr** [comment]
Hey @bchiaruttini I'm working my way through the banner UI now - as we discussed it makes sense to mirror the flash message, which has the following structure:
![image](https://user-images.githubusercontent.com/5726612/77470131-92249c80-6de6-11ea-91fa-a4af44cd6ab6.png)
We can easily reuse the styling for the title and message portion, and I will of course add a link to the COVID page.  The 'X' button doesn't make as much sense in this case - I could add a 'Dismiss Alert' button below the link instead of the 'X' so people understand the action they're taking a bit better.

Let me know what you would like to display for the title and message portion of the alert!

**Comment by bchiaruttini** [comment]
Got it, thanks. I think I would still understand the X to dismiss, but definitely default to you if you think "dismiss alert" is more logical.
Let's go with:
Title: In this time of public uncertainty, MARE is committed to continuing our mission to find adoptive homes for children and teens in foster care. 
Message: Read about MARE's COVID-19 Response here.

**Comment by n-devr** [comment]
Got it, thanks! Here's what that looks like on my local:

![image](https://user-images.githubusercontent.com/5726612/77476229-93f35d80-6df0-11ea-91ee-2330a6f58ed1.png)

I still have to make the message animate in and out, but I'm almost done.  Let me know if you want to tweak the design at all.

**Comment by bchiaruttini** [comment]
Design looks great, thanks

**Comment by n-devr** [comment]
Perfect! I'm gonna take a break then finish this story up.  Assuming I'm all clear to push this and the fix for the COVID-19 featured item to prod tonight?

**Comment by bchiaruttini** [comment]
yes can push anytime tonight

**Comment by n-devr** [comment]
Alright @bchiaruttini the banner is working and ready for you to take a look at in develop.  Once you dismiss the alert it will not appear again until you close the current tab or the browser.  That means a user can refresh, navigate to other pages, log in/out and the alert will remain dismissed.  Let me know if it looks good to you and I'll push to prod!
