### ISSUE TITLE
changes to child registration confirmation email

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#528]
Make content/structural changes to confirmation of child registration email: 
[Child Reg changes.docx](https://github.com/mareinc/mare/files/4736638/Child.Reg.changes.docx)

**Comment by n-devr** [comment]
This turned out to be a little more nuanced than it looked at first glance - below are a few questions I had as I went through the list of updates:

- Some fields that are currently displayed were left off the list (not crossed out, but not included either) - should they be removed from the email?
  - child alias
  - child nickname
  - has contact with siblings
  - type of contact with siblings
  - has contact with birth family
  - type of contact with birth family
  - care facility name
  - disabilities
  - other information about child's ethnic background
  - reason same-sex couples should not be considered
 - The `secondaryADLUworker` and `adoptionAssessment` fields are moved out of the 'fields that need to be set manually' section, but are not automatically set on the child record at registration.  My assumption is that they should be set automatically, but we'd need to make a change to the registration flow to make that happen.
 - The 'The following is additional relevant information that is not part of the new child record, but will help in adjusting values and understanding submitted information' and 'In addition, the following fields will need to be reviewed and manually updated in the new system' were merged, but I'm a little confused about how to implement.  The review/manual update section is just a list:
 ![image](https://user-images.githubusercontent.com/5726612/84422516-24b92880-abeb-11ea-9279-843b3f0a8462.png)
 However, the 'additional information' section includes the values that were entered in the 
 registration form.  Is the intent of this update to carry all of the information over an have a 
 value for every item in the combined list?  If not, which fields should have values?

**Comment by bchiaruttini** [comment]
@n-devr see my comments below in bold.  I'm around today if not clear and want to discuss further!

Some fields that are currently displayed were left off the list (not crossed out, but not included either) - should they be removed from the email?  **Sorry, realizing I was working off a sample email that only reflected the mandatory fields so missed all these others.  Yes they should all still be in the email if data was entered**
child alias
child nickname
has contact with siblings
type of contact with siblings
has contact with birth family
type of contact with birth family
care facility name
disabilities
other information about child's ethnic background
reason same-sex couples should not be considered

The secondaryADLUworker and adoptionAssessment fields are moved out of the 'fields that need to be set manually' section, but are not automatically set on the child record at registration. My assumption is that they should be set automatically, but we'd need to make a change to the registration flow to make that happen.  **There is no field in the child record to capture this info, which was intentional. It's only relevant upon first referral so as long as it is in the email nothing further needs to happen in the record, manually or automatically**

The 'The following is additional relevant information that is not part of the new child record, but will help in adjusting values and understanding submitted information' and 'In addition, the following fields will need to be reviewed and manually updated in the new system' were merged, but I'm a little confused about how to implement. The review/manual update section is just a list:
image
However, the 'additional information' section includes the values that were entered in the
registration form. Is the intent of this update to carry all of the information over an have a
value for every item in the combined list? If not, which fields should have values?
**I see what you are saying here.  This section is both a way to communicate data entered in form, as well as a prompt to the recipient that they have to do some of their own work.
So the fields that should correlate with values entered would be:
recruitment worker: 
recruitment worker agency:
recruitment worker email: 
recruitment worker phone:
adoption worker 
adoption worker agency: 
adoption worker email:  
adoption worker phone: 
siblings to be placed with
sibling name(s)
And then the items on list that do NOT correlate with values are
Child is Visible To
registered by 
physical needs 
emotional needs 
intellectual needs 
social needs 
.**

**Comment by bchiaruttini** [comment]
@n-devr tested and ready to push
