### ISSUE TITLE
Change to Event Registration Confirmation Email

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#777]
When a user registers for an event, confirmation email generated and is sent to MARE staff.  Pls change the reply field to prepopulate to the users email, instead of web@mareinc.org (as is currently.)

**Comment by durlabhcodes** [comment]
Are these issues up for grab?

**Comment by n-devr** [comment]
Unfortunately this one isn't possible.  In order to send emails on behalf of a user (e.g. so that they'd seem as if they came from `user@gmail.com`), we'd need to have DNS records set up to give Mandrill permission to send from that domain.

Without those DNS records, we get the following error:
```
  {
    email: noahweinert@gmail.com',
    status: 'rejected',
    _id: 'c239969799ba4dcfa766304f1c51c661',
    reject_reason: 'unsigned'
  }
```

We could look into editing the email template to add a shortcut to create an email to the registering user, so it'd still be a single click to reply to them, but we can't make the actual reply button function that way.
